<a href="https://colab.research.google.com/github/Chandayadav123/py/blob/master/Home_Price_prediction_%2C_MLR_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
from sklearn import linear_model

In [2]:
df = pd.read_csv('Book1.csv')
df

area  bedrooms  age   price
0  2600       3.0   20  560000
1  3000       4.0   15  565000
2  3200       NaN   18  610000
3  3600       3.0   30  620000
4  4000       5.0    8  760000
5  4100       6.0    8  810000

In [3]:
df.bedrooms.median()

4.0

In [7]:
df.bedrooms =df.bedrooms.fillna(df.bedrooms.median())

In [10]:
reg =linear_model.LinearRegression()
reg.fit(df.drop('price',axis='columns'),df.price)

LinearRegression()

In [11]:
reg.coef_

array([  121.97249473, 18917.23497293, -2387.52822651])

In [12]:
reg.intercept_


197999.7130147798

In [13]:
reg.predict([[3000, 3, 40]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([525167.77307021])

In [15]:
112.06244194*3000 + 23388.88007794*3 + -3231.71790863*40 + 197999.7130147798

475084.9627233998

In [16]:
reg.predict([[2500, 4, 5]])

/usr/local/lib/python3.7/dist-packages/sklearn/base.py:451: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  "X does not have valid feature names, but"


array([566662.24860472])